---
remote_upload_path: "{{ ansible_user_dir }}/Library/Caches/XcodeInstall"

xcode_src: "xcode/Xcode_11.3.1.xip"
xcode_url: "https://download.developer.apple.com/Developer_Tools/Xcode_11.3.1/Xcode_11.3.1.xip"
xcode_sha1sum: "d5773e61189595cbb639c3e1c460b38d8c1e19ae"
xcode_packages_path: /Applications/Xcode.app/Contents/Resources/Packages
xcode_xip_path: "{{ remote_upload_path }}/{{ xcode_src | basename }}"

xcode_clt_src: "xcode/Command_Line_Tools_for_Xcode_11.3.1.dmg"
xcode_clt_url: "https://download.developer.apple.com/Developer_Tools/Command_Line_Tools_for_Xcode_11.3.1/Command_Line_Tools_for_Xcode_11.3.1.dmg"
xcode_clt_sha1sum: "cec5824d127bba2d2a3ba8e5343ae7a32214e62c"
xcode_clt_dmg_path: "{{ remote_upload_path }}/{{ xcode_clt_src | basename }}"
xcode_clt_pkg_path: "/Volumes/Command Line Developer Tools/Command Line Tools.pkg"
