- name: Install requred packages
  apt: 
    name: "{{ deb_packages }}"
    force: yes 
  become: yes

- name: Install java repo
  apt_repository:
    repo: "{{ java_repo }}"
    filename: java
  become: yes

- name: Install java
  apt:
    name: "{{ java_package }}"
    force: yes
  become: yes

- name: Install qt repo
  apt_repository:
    repo: "{{ qt_repo }}"
    filename: qt

- name: Install qt
  apt:
    name: "{{ qt_package }}"
    force: yes

- name: Fix qt 3rd party location
  shell: test -h /usr/lib/x86_64-linux-gnu/libpng12.so.0 && unlink /usr/lib/x86_64-linux-gnu/libpng12.so.0 && cp /lib/x86_64-linux-gnu/libpng12.so.0 /usr/lib/x86_64-linux-gnu
  become: yes
  ignore_errors: yes

- name: Install patchelf repo
  apt_repository:
    repo: "{{ patchelf_repo }}"
    filename: qt

- name: Install patchelf
  apt:
    name: "{{ patchelf_package }}"
    force: yes

- name: Install grunt
  npm: name=grunt-cli global=yes
  become: yes

- name: Install pkg
  npm: name=pkg global=yes
  become: yes