---
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yaml"

- name: Include windows architecture variables.
  include_vars: "{{ ansible_os_family }}-{{ ansible_architecture }}.yaml"
  when: ansible_os_family == "Windows"

- name: Include OS-specific task.
  include_tasks: "{{ ansible_os_family }}.yaml"
