deb_packages:
  - apt-transport-https
  - autoconf
  - build-essential
  - createrepo
  - debhelper
  - desktop-file-utils
  - dpkg-dev
  - git
  - libatk1.0-dev
  - libcairo2-dev
  - libcurl4-gnutls-dev
  - libgconf2-dev
  - libgdk-pixbuf2.0-dev
  - libglib2.0-dev
  - libgtkglext1-dev
  - libtool
  - libxml2-dev
  - libxss-dev
  - p7zip-full
  - qtchooser
  - software-properties-common
  - sed
  - subversion
  - symlinks
  - tar
  - wget
  - unzip

java_repo: ppa:openjdk-r/ppa
java_package: openjdk-8-jdk

qt_repo: ppa:beineri/opt-qt596-trusty
qt_package: qt59-meta-full

patchelf_repo: ppa:cjwatson/backports
patchelf_package: patchelf