---
program_files: "{{ program_files_32 }}"

packages:
  - name: 7-Zip
    url: https://www.7-zip.org/a/7z1900.msi
    product_id: '{23170F69-40C1-2701-1900-000001000000}'
    arguments: '{{ msi_args }}'
    path: "{{ download_path }}\\7z.msi"

  - name: AWSCLI
    url: https://s3.amazonaws.com/aws-cli/AWSCLI32.msi
    product_id: '{F5ED6807-D6BC-47B0-BA90-E83FBB644079}'
    arguments: '{{ msi_args }}'
    path: "{{ download_path }}\\aws-cli.msi"

  - name: Git
    url: https://npm.taobao.org/mirrors/git-for-windows/v2.21.0.windows.1/Git-2.21.0-32-bit.exe
    product_id: 'Git_is1'
    arguments: '{{ innosetup_args }}'
    path: "{{ download_path }}\\git.exe"

  - name: Inno Setup
    url: http://files.jrsoftware.org/is/5/innosetup-5.6.1-unicode.exe
    product_id: 'Inno Setup 5_is1'
    arguments: '{{ innosetup_args }}'
    path: "{{ download_path }}\\is-unicode.exe"

  - name: Java
    url: http://download.oracle.com/otn-pub/java/jdk/8u131-b11/d54c1d3a095b4ff2b6607d096fa80163/jdk-8u131-windows-x64.exe
    product_id: '{26A24AE4-039D-4CA4-87B4-2F64180131F0}'
    arguments: '{{ java_args }}'
    path: "{{ download_path }}\\java.exe"
    headers: 
      Cookie: "oraclelicense=accept-securebackup-cookie"

  - name: Node.js
    url: https://nodejs.org/dist/v10.17.0/node-v10.17.0-x86.msi
    product_id: '{9A3F4E8A-0D91-4ECE-868B-9C776371201D}'
    arguments: '{{ msi_args }}'
    path: "{{ download_path }}\\node.msi"

  - name: Python 2.7
    url: https://www.python.org/ftp/python/2.7.16/python-2.7.16.msi
    product_id: '{DCD5B320-89D9-4C7C-9E8B-84496588744D}'
    arguments: '{{ msi_args }}'
    path: "{{ download_path }}\\python27.msi"

  - name: Visual Studio Community 2015
    url: https://download.microsoft.com/download/e/4/c/e4c393a9-8fff-441b-ad3a-3f4040317a1f/vs_community.exe
    product_id: '{79b486b9-c5f0-4096-a00c-8351f59587c2}'
    arguments: '{{ vs_args }}'
    path: "{{ download_path }}\\vs.exe"

  - name: Windows 10 SDK
    url: http://download.microsoft.com/download/C/D/8/CD8533F8-5324-4D30-824C-B834C5AD51F9/standalonesdk/sdksetup.exe
    product_id: '{5eb6fbea-73ee-4a8e-9042-110704768d7f}'
    arguments: '{{ w10sdk_args }}'
    path: "{{ download_path }}\\w10sdk.exe"

  - name: Tortoise svn
    url: https://dotsrc.dl.osdn.net/osdn/storage/g/t/to/tortoisesvn/1.10.5/Application/TortoiseSVN-1.10.5.28651-x64-svn-1.10.6.msi
    product_id: '{629C95E8-10D9-4F05-8958-DC66A5A72925}'
    arguments: "{{ svn_args }}"
    path: "{{ download_path }}\\svn.msi"

  - name: MSYS2
    url: http://repo.msys2.org/distrib/i686/msys2-i686-20180531.exe
    product_id: '{5e49e0c3-49c3-4663-9f0d-67997ce9235a}'
    creates_path: "{{ msys2_path }}"
    arguments: '{{ msys2_args }}'
    path: "{{ download_path }}\\msys2.exe"

  - name: QT 5.9
    url: https://download.qt.io/official_releases/qt/5.9/5.9.8/qt-opensource-windows-x86-5.9.8.exe
    product_id: '{88d6f945-e1bf-4b45-96d3-3568988b15de}'
    creates_path: "{{ qt_path }}"
    arguments: '{{ qt_args }}'
    path: "{{ download_path }}\\qt.exe"

  - name: QT 5.6
    url: http://download.qt.io/new_archive/qt/5.6/5.6.3/qt-opensource-windows-x86-msvc2015-5.6.3.exe
    product_id: '{a6de10bd-9db8-4d6b-bb0b-22bc2da648b0}'
    creates_path: "{{ qt56_path }}"
    arguments: '{{ qt56_args }}'
    path: "{{ download_path }}\\qt56.exe"

  - name: Strawberry Perl 5.30.2.1
    url: http://strawberryperl.com/download/5.30.2.1/strawberry-perl-5.30.2.1-32bit.msi
    product_id: '{2E2B305B-6E94-1014-A14A-250D35D88115}'
    creates_path: C:\Strawberry
    arguments: "{{ msi_args }}"
    path: "{{ download_path }}\\strawberry-perl.msi"

  - name: NASM 2.14.02
    url: https://www.nasm.us/pub/nasm/releasebuilds/2.14.02/win32/nasm-2.14.02-installer-x86.exe
    product_id: ''
    creates_path: "{{ program_files_32 }}\\NASM"
    arguments: "/S"
    path: "{{ download_path }}\\nasm.exe"

mingw_packages:
  - name: Mingw
    url: https://sourceforge.net/projects/mingw-w64/files/Toolchains%20targetting%20Win32/Personal%20Builds/mingw-builds/8.1.0/threads-win32/sjlj/i686-8.1.0-release-win32-sjlj-rt_v6-rev0.7z
    path: "{{ download_path }}\\mingw.7z"

exec_path:
  - '%SystemDrive%\Python27'
  - '{{ qt_path }}\5.9.8\msvc2015\bin'
  - '{{ mingw_path }}\mingw32\bin'
  - '{{ msys2_path }}\usr\bin'
  - '{{ program_files_32 }}\7-Zip'
  - '{{ program_files_32 }}\Git\cmd'
  - '{{ program_files_64 }}\TortoiseSVN\bin'
  - '%SystemDrive%\Windows\ServiceProfiles\LocalService\AppData\Roaming\npm'
  - '{{ program_files_32 }}\Inno Setup 5'
  - '{{ program_files_32 }}\Microsoft Visual Studio 14.0\VC\bin'
  - '{{ program_files_32 }}\Windows Kits\10\bin\x86'
  - '{{ program_files_32 }}\NASM'
  - '%SystemDrive%\Strawberry\c\bin'
  - '%SystemDrive%\Strawberry\perl\site\bin'
  - '%SystemDrive%\Strawberry\perl\bin'

innosetup_path: "{{ program_files_32 }}\\Inno Setup 5"
